---
include:
  - board: nice_nano
    shield: sofle_left prospector_adapter prospector_left_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: nice_sofle_left_prospector
  - board: nice_nano
    shield: sofle_right
    artifact-name: nice_sofle_right_touchpad_peripheral
  - board: nice_nano
    shield: settings_reset
    artifact-name: nice_nano_settings_reset
